# compose.yml

services:
  slidev:
    image: oven/bun:latest
    # build: slides.Dockerfile
    working_dir: /slides
    volumes:
      - .:/slides
    environment:
      - ROLLUP_USE_WASM=true
    # Dev:
    command: >
      sh -c "bun install &&
             bun run slidev --port 3000 --remote"
    ports:
      - "3000:3000"
    # Prod:
    # command: >
    #   sh -c "bun install &&
    #          bunx slidev build &&
    #          bunx serve -s dist -l 3000"
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /slides
    #       ignore:
    #         - node_modules/
    networks:
      - workshop

  dind-runner:
    build:
      context: .
      dockerfile: dind_runner/Dockerfile
    image: dind-runner
    profiles: ["build-only"] # not a service just build it

  proxy:
    image: python:3.12-slim-bookworm
    working_dir: /app
    volumes:
      - ./ws_proxy_server.py:/app/ws_proxy_server.py
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5000
    entrypoint: >
      sh -c "apt-get update && apt-get install -y docker.io &&
             pip install uvicorn fastapi websockets docker &&
             uvicorn ws_proxy_server:app --proxy-headers --forwarded-allow-ips='*'"
    ports:
      - "5000:5000"
    networks:
      - workshop

networks:
  workshop:
    driver: bridge
