#!/usr/bin/env just --justfile
set unstable

dind-runner-build:
    docker build -t dind-runner dind_runner


dind-server:
    DEBUG=1 uv run docker_session_server.py

[script("bash")]
dind-test:
    sess_json=$(curl -X POST http://localhost:5000/session \
        -H "Content-Type: application/json" \
        -d '{"wait": "true", "timeout": "15"}')
    sess_id=$(echo "$sess_json" | jq -r ".id")
    sess_port=$(echo "$sess_json" | jq -r ".port")
    echo "Started Session: ID=$sess_id Port: $sess_port"
    echo "Running command"
    endpoint="http://127.0.0.1:5000/run?sess=$sess_id"
    echo "Endpoint: $endpoint"
    curl -X POST $endpoint \
    -H "Content-Type: application/json" \
    -d '{"cmd": "docker run hello-world", "debug": "false"}'
    docker logs -f $sess_id
    curl -X DELETE http://localhost:5000/session?sess=$sess_id
